// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdzNPWTfq4nt_qgCt47fT0tSxz-LFAFLE',
    appId: '1:472313342665:web:0d56aa7b5ea73030257b18',
    messagingSenderId: '472313342665',
    projectId: 'main-project-9d535',
    authDomain: 'main-project-9d535.firebaseapp.com',
    storageBucket: 'main-project-9d535.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77sBu1FdGPf_NjZB_P5tvxDvPiLYe_pE',
    appId: '1:472313342665:android:eeb4e798c4d8a5d1257b18',
    messagingSenderId: '472313342665',
    projectId: 'main-project-9d535',
    storageBucket: 'main-project-9d535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIJpXIdCuv-G_HF5Xkrr6WBnadNOhdLXY',
    appId: '1:472313342665:ios:a67db2b526054e44257b18',
    messagingSenderId: '472313342665',
    projectId: 'main-project-9d535',
    storageBucket: 'main-project-9d535.appspot.com',
    iosBundleId: 'com.example.mainProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIJpXIdCuv-G_HF5Xkrr6WBnadNOhdLXY',
    appId: '1:472313342665:ios:1fb2fdc73f6a8433257b18',
    messagingSenderId: '472313342665',
    projectId: 'main-project-9d535',
    storageBucket: 'main-project-9d535.appspot.com',
    iosBundleId: 'com.example.mainProject.RunnerTests',
  );
}
